### ISSUE TITLE
Feature Suggestion: Detailed Info About Apps and Downloads

### ISSUE THREAD

**Issue by MainUserA** [mjishnu/alt-app-installer#51]
Hi, first off I'd like to thank you for putting the time and effort into this awesome program it really eased the process of Installing apps.

Now, I would like to suggest enhancing this app by making it display detailed information about the app we're going to install (name, size, icon,...etc) and also making that when downloading an app from the built-in browser the program displays info about the app and the download process (download speed, download progress in percentage,...etc) also allowing for pausing and resuming downloads.

Also, one last thing, I'm wondering if it's possible to extract the installed app into an installation package so we don't need to redownload it again.

I really hope you consider adding these features in the next update as it will really enhance the program in my opinion, good luck.

**Comment by mjishnu** [comment]
about app info its should already be present in the page where you select the app

the progress bar shows the progress, i intentionally didn't add much details to the download to make it simpler

pause resume functionality is already present hit stop when you want to pause. the download afterwards select the same app again then it will resume the download

the downloaded apps are stored in downloads folder (options --> downloads)

**Comment by MainUserA** [comment]
Wow! 😅 but also I just wanted the program to be elegant and reliable instead of everything being separated. Thanks for the info though.

**Comment by mjishnu** [comment]
I am planning on rebuilding the app from scratch using winui3.

**Comment by MainUserA** [comment]
> regarding ui improvement, I am planning on rebuilding the app from scratch using winui3 don't ask the eta as i am doing it in my free time.

That's awesome! Take as much time as you need and we'll patiently wait for you. Good luck, thanks for this.
