### ISSUE TITLE
python312.dll wont initialize

### ISSUE THREAD

**Issue by Magic-Man000104** [mjishnu/alt-app-installer#58]
python312.dll doesn't want to initialize after installing unofficial Python 3.12.4 for windows 7 unless you use VxKex in which most functionality no longer Works in the way it was intended,

https://github.com/adang1345/PythonWin7/blob/master/3.12.4/python-3.12.4-amd64-full.exe

https://github.com/vxiiduu/VxKex/

**Comment by mjishnu** [comment]
this app doesn't support [windows 7](https://github.com/mjishnu/alt-app-installer?tab=readme-ov-file#requirements). you can try building from source if its throwing errors try using old version of dependencies.
