### ISSUE TITLE
arm64 support 

### ISSUE THREAD

**Issue by xgdgsc** [mjishnu/alt-app-installer#59]
https://github.com/mjishnu/alt-app-installer/blob/3619afce0a348b3e197daa5cc667a59631fe7306/app/modules/url_gen.py#L27

I had to change this to return "arm64" to download successfully.

The arm version Python PyQt6 has some installation issues so I have to run the x64 Python version. Maybe adding an arm64 checkbox now can be fine.

And how to do the packaging to exe?

**Comment by mjishnu** [comment]
hey would you be willing to test this, i do not own an arm pc so was unable to test it

```py
import platform

def os_arc():
    if platform.machine().endswith("64"):
        return "x64"
    if platform.machine().endswith("32") or platform.machine().endswith("86"):
        return "x86"
    if platform.machine().endswith("arm64"):
        return "arm64 endswith success"
    if platform.machine().endswith("arm"):
        return "arm endswith success"
    if platform.machine().startswith("arm64"):
        return "arch64 startswith success"
    if platform.machine().startswith("arm"):
        return "arch startswith success"

print(os_arc())
```
what does the output shows ?

if this works we dont need a toggle it will automatically figure it out, the packaging is done using [pyinstaller](https://pyinstaller.org/en/stable/)

**Comment by xgdgsc** [comment]
![image](https://github.com/mjishnu/alt-app-installer/assets/1189869/bf8c1973-527e-4633-8854-cd8dd7ae33f1)
The problem for me is installing pyqt6 on arm64 python.

**Comment by mjishnu** [comment]
```py
def os_arc():
    machine = platform.machine().lower()

    if machine.endswith("arm64"):
        return "arm64"
    if machine().endswith("64"):
        return "x64"
    if machine.endswith("32") or machine.endswith("86"):
        return "x86"
    else:
        return "arm"

print(os_arc())
```
can you try now,  i see that even if i do a logic like this it would be waste since you are not able to run it in arm64 python but still in future it might work so if you can please provide output of this test it would be great.

> The problem for me is installing pyqt6 on arm64 python. Or provide a cli version could be fine.

try older version of pyqt, currently i am rewriting the program from scratch to c#, and not doing any major changes. let me see what i can do about cli if it aint too complicated i would implement it.

**Comment by xgdgsc** [comment]
This is fine.
```
>>> print(os_arc())
arm64
```

**Comment by mjishnu** [comment]
here is a cli version of alt app installer: https://github.com/mjishnu/alt-app-installer-cli

**Comment by xgdgsc** [comment]
![image](https://github.com/mjishnu/alt-app-installer/assets/1189869/bacf39f2-0537-4f2f-bcfa-4cb23e18b599)
Guess this is because arm python cannot load the dll?

**Comment by mjishnu** [comment]
did you install python net

**Comment by mjishnu** [comment]
> ![image](https://private-user-images.githubusercontent.com/1189869/341370358-bacf39f2-0537-4f2f-bcfa-4cb23e18b599.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4ODg4MzUsIm5iZiI6MTcxODg4ODUzNSwicGF0aCI6Ii8xMTg5ODY5LzM0MTM3MDM1OC1iYWNmMzlmMi0wNTM3LTRmMmYtYmNmYS00Y2IyM2UxOGI1OTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjBUMTMwMjE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2JlZjFhNTZhYTYwODRjN2YwYmNmZDY3ZmQxYjc4YjJjYTY4ZGY2MjE5OWRhNDFjZTg2ODQzYzExMGU3ODFhNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Kf8K6hDbVxFBdu5BeSpqSpM1Bdd90YIOWtt8dc2wMtI) Guess this is because arm python cannot load the dll?

this new release should fix it, no longer using python net using subprocess module instead 
https://github.com/mjishnu/alt-app-installer-cli/releases/tag/v1.0.1

**Comment by xgdgsc** [comment]
Great. It works.

**Comment by mjishnu** [comment]
> Great. It works. Might as well adding argument for downloading for other manually specified architecture, rather than relying on the interpreter arch?

i know its been long but if you are still wondering i have added the option to set custom architecture in [alt app installer cli](https://github.com/mjishnu/alt-app-installer-cli/releases/tag/v1.1.0)
