### ISSUE TITLE
python312.DLL initialization failed

### ISSUE THREAD

**Issue by BrambleTheUniversal** [mjishnu/alt-app-installer#63]
I'm a linux user that wants to use this to download paint 3D, but I keep running into an error that the DLL Initialization failed when i try to open the exe file using wine. Is there a way to fix this or am i just unable to use this method?

**Comment by mjishnu** [comment]
this is probably a duplication of #58, as i have said there if the .exe is not working try building from source if its throwing errors try using old version of dependencies or use the [cli version](https://github.com/mjishnu/alt-app-installer-cli)
