### ISSUE TITLE
Alternative Download Method for Microsoft Store App

### ISSUE THREAD

**Issue by technicalrubics** [mjishnu/alt-app-installer#67]
Hi everyone,

I need to download an app, which is only available on the Microsoft Store. Here is the link to the app I need:(https://apps.microsoft.com/detail/9nsm4kxxxqh8?hl=en-us&gl=US).

Unfortunately, the Microsoft Store is currently blocked on my network, and I’m unable to download it directly. Does anyone know of a way to obtain the app without accessing the Microsoft Store, or any alternative methods for downloading Store-only apps?

Thanks in advance for any help!

**Comment by mjishnu** [comment]
open alt app installer go to options--> get from link --> paste the link get the app
