### ISSUE TITLE
Can't get the latest version of WhatsApp

### ISSUE THREAD

**Issue by FaithfulObserver** [mjishnu/alt-app-installer#69]
I found that downloading WhatsApp this time could not get the latest version, 2.2446.6.0. Only version 2.2445.7.0. Deleting the cache folder has been done but still does not work.

**Comment by mjishnu** [comment]
![image](https://github.com/user-attachments/assets/1779a749-bda3-49e8-8509-1d3d90968693)
hello, i think its slowly rolling out in various regions in my region the latest is .445 and .446 is not released yet wait a few days it should update

the current version of alt app installer uses USA as [the region](https://github.com/mjishnu/alt-app-installer/blob/6f099bb6e5abea4295cf3240be29d99cc18b93c2/app/modules/url_gen.py#L435) also i am not sure if its rolling in some places in us and not in others etc. so my current suggestion is to wait a few more days and check if it gets released globally you should get it via alt app installer too
